#' Returns a data table of aggregated accelerometer data 
#' 
#' The function takes in as parameters, locations of data files, loads those files into data tables
#' and then binds the data where we can accelerometer data generated by a subject performing a given activity.
#' 
#' @param featuresFile the relative location of the features file
#' @param activityLabelsFile the relative location of the activities file
#' @param subjectsFile the relative location of the subjects file
#' @param xDataFile the relative location of the x data file
#' @param xDataFile the relative location of the y data file
extractRawData <- function(featuresFile, activityLabelsFile, subjectsFile, xDataFile, yDataFile) {
    subjects <- read.table(trainSubjectsFile, col.names = c("Subject"))
    
    features <- read.table(featuresFile, col.names = c("Feature ID", "Feature"))
    
    activityLabels <- read.table(activityLabelsFile, col.names = c("Activity ID", "Activity"))
    
    xData <- read.table(trainXDataFile, col.names = features$Feature)  
    
    yData <- read.table(trainYDataFile, col.names=c("Activity ID"))
    
    rawData <- cbind(subjects, yData, xData)
    
    rawData <- merge(activityLabels, rawData, by.x="Activity.ID", by.y="Activity.ID", sort = FALSE)
    
    return(rawData)
}


# defining the locations of the data files
featuresFile <- "UCI HAR Dataset//features.txt"
activityLabelsFile <- "UCI HAR Dataset//activity_labels.txt"

trainSubjectsFile <- "UCI HAR Dataset//train//subject_train.txt"
trainXDataFile <- "UCI HAR Dataset//train//X_train.txt"
trainYDataFile <- "UCI HAR Dataset//train//y_train.txt"

testSubjectsFile <- "UCI HAR Dataset//train//subject_train.txt"
testXDataFile <- "UCI HAR Dataset//test//X_train.txt"
testYDataFile <- "UCI HAR Dataset//test//y_train.txt"

# Extract training and test data
trainRawData <- extractRawData(featuresFile, activityLabelsFile, trainSubjectsFile, trainXData, trainYData)
testRawData <- extractRawData(featuresFile, activityLabelsFile, testSubjectsFile, testXDataFile, testYDataFile)

# Merge training and test data
mergedRawData <- rbind(trainRawData, testRawData)
subject <- mergedRawData$Subject
activity <- mergedRawData$Activity

# Prune columns that are include std or mean
dataColNames <- colnames(mergedRawData)
stdMeanColNames <- dataColNames[grep("std\\.|mean\\.", colnames(mergedRawData))]
prunedData <- subset(mergedRawData, select = stdMeanColNames)

# Change the column names to be more descriptive
descriptiveDataNames <- stdMeanColNames
descriptiveDataNames <- gsub("\\.", "", descriptiveDataNames)
descriptiveDataNames <- gsub("\\X", "-X", descriptiveDataNames)
descriptiveDataNames <- gsub("\\Y", "-Y", descriptiveDataNames)
descriptiveDataNames <- gsub("\\Z", "-Z", descriptiveDataNames)
descriptiveDataNames <- gsub("mean", "-mean", descriptiveDataNames)
descriptiveDataNames <- gsub("std", "-std", descriptiveDataNames)
names(prunedData) <- descriptiveDataNames

# Aggregate data by subject and activity
agg <- aggregate(prunedData, list(Subject = subject, Activity = activity), FUN=mean)
sortagg <- agg[order(agg$Subject, agg$Activity),]

# Write out data as csv but with  a txt extension
write.table(sortagg, "tidyData.txt", sep="\t", quote=FALSE, row.names=FALSE)